#spring.data.mongodb.uri= mongodb+srv://anbag2003_db_user:YF9C0VDZ6JqDJRLi@springboot.48sksq8.mongodb.net/?appName=SpringBoot
#spring.data.mongodb.database=journaldb
#
#spring.data.mongodb.auto-index-creation=true
#
#server.port=8081
#server.=/journal
#
